name: Build and release

permissions:
    contents: write

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup Node v18.1
              uses: actions/setup-node@v3
              with:
                  node-version: '18.1'
                  cache: 'yarn'
            - run: yarn install --frozen-lockfile
            - run: yarn build:prod
            - name: Generate release file
              uses: ncipollo/release-action@v1
              with:
                  artifacts: 'build.js'
                  artifactContentType: 'text/javascript'
                  tag: latest
                  commit: ${{github.sha}}
